desc "Return %h %s format commit log"
private_lane :changelog_from_git_commits_hs do
  changelog_from_git_commits(
    between: ["HEAD^", "HEAD"],
    pretty: '%h %s'
  )
end


desc "Return difference from last tag or first commit"
private_lane :git_tag_diff do
  from = last_git_tag || sh('git rev-list --max-parents=0 HEAD')[0,7]
  changelog_from_git_commits(
    between: [from, "HEAD"],
    pretty: '%h %s'
  )
end


desc "Reset diff"
private_lane :reset_diff do
  # build_id 更新で差分が出る project.pbxproj のみ復元する
  sh('cd $(git rev-parse --show-cdup) && git checkout -- ":(glob)**/project.pbxproj" 2>/dev/null || true')
end
