# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    now = Time.now.to_i
    sh("flutter build appbundle --release --build-number=#{now}")

    # 環境変数から設定を読み込んでアップロード
    upload_to_play_store(
      track: ENV['SUPPLY_TRACK'] || 'production',
      aab: ENV['SUPPLY_AAB'] || "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: ENV['SUPPLY_SKIP_UPLOAD_METADATA'] == 'true',
      skip_upload_changelogs: ENV['SUPPLY_SKIP_UPLOAD_CHANGELOGS'] == 'true',
      skip_upload_images: ENV['SUPPLY_SKIP_UPLOAD_IMAGES'] == 'true',
      skip_upload_screenshots: ENV['SUPPLY_SKIP_UPLOAD_SCREENSHOTS'] == 'true',
      release_status: ENV['SUPPLY_RELEASE_STATUS'] || 'draft'
    )
  end
end
